#include <linux/ioctl.h>

#define NMC3_IOCTL_MAGIC 'N'

#define IOCTL_NMC3_SEND_NMI _IO(NMC3_IOCTL_MAGIC, 0)
#define IOCTL_NMC3_SEND_HPINT _IO(NMC3_IOCTL_MAGIC, 1)
#define IOCTL_NMC3_SEND_LPINT _IO(NMC3_IOCTL_MAGIC, 2)

#define IOCTL_NMC3_MASK_HP_INTERRUPT _IOW(NMC3_IOCTL_MAGIC, 3, __u32)
#define IOCTL_NMC3_MASK_LP_INTERRUPT _IOW(NMC3_IOCTL_MAGIC, 4, __u32)
#define IOCTL_NMC3_WAIT_HP_INTERRUPT _IOWR(NMC3_IOCTL_MAGIC, 5, __u32)
#define IOCTL_NMC3_WAIT_LP_INTERRUPT _IOWR(NMC3_IOCTL_MAGIC, 6, __u32)
#define IOCTL_NMC3_CANCEL_WAIT_HP_INTERRUPT _IO(NMC3_IOCTL_MAGIC, 7)
#define IOCTL_NMC3_CANCEL_WAIT_LP_INTERRUPT _IO(NMC3_IOCTL_MAGIC, 8)

#define IOCTL_NMC3_WAIT_SYSTEM_INTERRUPT _IOWR(NMC3_IOCTL_MAGIC, 9, __u64)
#define IOCTL_NMC3_RESET_SYSTEM_INTERRUPT _IO(NMC3_IOCTL_MAGIC, 10)
#define IOCTL_NMC3_USER_CORE_UNLOCK _IO(NMC3_IOCTL_MAGIC, 11)

#define IOCTL_NMC3_RESET _IO(NMC3_IOCTL_MAGIC, 12)

#ifdef UNDOC
#define IOCTL_NMC3_GET_REG _IOWR(NMC3_IOCTL_MAGIC, 13, __u32)
#define IOCTL_NMC3_SET_REG _IOW(NMC3_IOCTL_MAGIC, 14, __u64)
#endif // UNDOC
