obj-$(CONFIG_EASYNMC) += easynmc.o
obj-$(CONFIG_EASYNMC_CORE_TEST) += easynmc-core-test.o
obj-$(CONFIG_EASYNMC_CORE_NMC3) += easynmc-core-nmc3.o
obj-$(CONFIG_RCM_RMACE) += rcm-rmace.o
obj-$(CONFIG_RCM_DMA_TEST) += rcm-dma-test.o
obj-$(CONFIG_RCM_GPIO_EXTINT) += gpio-extint.o
obj-$(CONFIG_RCM_1879_MSVDHD) += msvdhd.o
