// ??? temp

#define VDU_REG_VDU_CTRL_BASE 0x000
#define VDU_REG_INT_BASE 0x300
#define VDU_REG_DIF_BASE 0x500


#define VDU_REG_CTRL_VDU_ID (VDU_REG_VDU_CTRL_BASE + 0x04)
#define VDU_REG_CTRL_ENA (VDU_REG_VDU_CTRL_BASE + 0x08)
#define VDU_REG_CTRL_SOFT_RESET (VDU_REG_VDU_CTRL_BASE + 0x0C)

#define VDU_REG_CTRL_ENA_VDU_ENA_MASK (1 << 0)

#define VDU_REG_CTRL_SOFT_RESET_MASK (1 << 0)


#define VDU_REG_INT_ENA (VDU_REG_INT_BASE + 0x04)
#define VDU_REG_INT_STAT (VDU_REG_INT_BASE + 0x08)

#define VDU_REG_INT_VDU_ENA_MASK (1 << 1)
// ??? #define VDU_REG_INT_VDU_STAT_V_SYNC_MASK (1 << 16)
#define VDU_REG_INT_VDU_STAT_SA_MASK		(1 << 18)


#define VDU_REG_DIF_CTRL (VDU_REG_DIF_BASE + 0x04)
#define VDU_REG_DIF_BGR (VDU_REG_DIF_BASE + 0x08)
#define VDU_REG_DIF_BLANK (VDU_REG_DIF_BASE + 0x10)
#define VDU_REG_DIF_FSIZE (VDU_REG_DIF_BASE + 0x14)
#define VDU_REG_DIF_ASIZE (VDU_REG_DIF_BASE + 0x18)
#define VDU_REG_DIF_HSYNC (VDU_REG_DIF_BASE + 0x1C)
#define VDU_REG_DIF_VSYNC (VDU_REG_DIF_BASE + 0x20)

// ??? #define VDU_REG_DIF_CTRL_SDTV_FORM_MASK	(1 << MVDU_REG_DIF_CTRL_SDTV_FORM_SHIFT)
// ??? #define VDU_REG_DIF_CTRL_INT_SYNC_EN_MASK	(1 << MVDU_REG_DIF_CTRL_INT_SYNC_EN_SHIFT)
// ??? #define VDU_REG_DIF_CTRL_VDU_MODE_SHIFT	0
// ??? #define VDU_REG_DIF_CTRL_VDU_MODE_MASK		(0x1F << MVDU_REG_DIF_CTRL_VDU_MODE_SHIFT)
#define VDU_REG_DIF_CTRL_EXT_SYNC_EN_MASK (1 << 9)
#define VDU_REG_DIF_CTRL_SDTV_FORM_MASK (1 << 10)
#define VDU_REG_DIF_CTRL_HSYNC_P_MASK (1 << 16)
#define VDU_REG_DIF_CTRL_VSYNC_P_MASK (1 << 17)
#define VDU_REG_DIF_CTRL_DIF_444_MODE_MASK (1 << 31)

#define VDU_REG_DIF_BGR_CR_SHIFT 0
#define VDU_REG_DIF_BGR_CB_SHIFT 8
#define VDU_REG_DIF_BGR_Y_SHIFT 16

#define VDU_REG_DIF_BLANK_HBLANK_SHIFT 0
#define VDU_REG_DIF_BLANK_VBLANK_BEG_SHIFT 16
#define VDU_REG_DIF_BLANK_VBLANK_END_SHIFT 24

#define VDU_REG_DIF_FSIZE_HTOTAL_SHIFT 0
#define VDU_REG_DIF_FSIZE_VTOTAL_SHIFT 16

#define VDU_REG_DIF_ASIZE_HACTIVE_SHIFT 0
#define VDU_REG_DIF_ASIZE_VACTIVE_SHIFT 16

#define VDU_REG_DIF_HSYNC_START_SHIFT 0
#define VDU_REG_DIF_HSYNC_LEN_SHIFT 16
#define VDU_REG_DIF_HSYNC_DELAY_SHIFT 24

#define VDU_REG_DIF_VSYNC_START_SHIFT 0
#define VDU_REG_DIF_VSYNC_LEN_SHIFT 16

// ??? down
#define MODULE_VDU_REGISTERS_SIZE		0x934

#define MVDU_VDU_STATUS_BASE			0x200
#define MVDU_VDU_SCALER_BASE			0x400
#define MVDU_VDU_OSD_BASE			0x700
#define MVDU_VDU_MI_BASE			0x900


#define MVDU_REG_CTRL_VDU_ENA_MVL_BASE_SW_ENA_SHIFT 9
#define MVDU_REG_CTRL_VDU_ENA_MVL_BASE_SW_ENA_MASK (1 << MVDU_REG_CTRL_VDU_ENA_MVL_BASE_SW_ENA_SHIFT)
#define MVDU_REG_CTRL_VDU_ENA_OSD_BASE_SW_ENA_SHIFT 8
#define MVDU_REG_CTRL_VDU_ENA_OSD_BASE_SW_ENA_MASK (1 << MVDU_REG_CTRL_VDU_ENA_OSD_BASE_SW_ENA_SHIFT)
#define MVDU_REG_CTRL_VDU_ENA_MVL_ENA_SHIFT	2
#define MVDU_REG_CTRL_VDU_ENA_MVL_ENA_MASK	(1 << MVDU_REG_CTRL_VDU_ENA_MVL_ENA_SHIFT)
#define MVDU_REG_CTRL_VDU_ENA_OSD_ENA_SHIFT	1
#define MVDU_REG_CTRL_VDU_ENA_OSD_ENA_MASK	(1 << MVDU_REG_CTRL_VDU_ENA_OSD_ENA_SHIFT)
#define MVDU_REG_CTRL_VDU_ENA_VDU_ENA_SHIFT	0

#define MVDU_REG_STAT_VDU_DISP			(MVDU_VDU_STATUS_BASE + 0x04)
#define MVDU_REG_STAT_VDU_DISP_FIELD_SHIFT	3
#define MVDU_REG_STAT_VDU_DISP_FIELD_MASK	(1 << MVDU_REG_STAT_VDU_DISP_FIELD_SHIFT)
#define MVDU_REG_STAT_VDU_DISP_HBB_SHIFT	2
#define MVDU_REG_STAT_VDU_DISP_HBB_MASK		(1 << MVDU_REG_STAT_VDU_DISP_HBB_SHIFT)
#define MVDU_REG_STAT_VDU_DISP_VBB_SHIFT	1
#define MVDU_REG_STAT_VDU_DISP_VBB_MASK		(1 << MVDU_REG_STAT_VDU_DISP_VBB_SHIFT)

#define MVDU_REG_STAT_VDU_AVMP			(MVDU_VDU_STATUS_BASE + 0x08)
#define MVDU_REG_STAT_VDU_AVMP_MVL_AVMP_SHIFT	1
#define MVDU_REG_STAT_VDU_AVMP_MVL_AVMP_MASK	(1 << MVDU_REG_STAT_VDU_AVMP_MVL_AVMP_SHIFT)
#define MVDU_REG_STAT_VDU_AVMP_OSD_AVMP_SHIFT	0
#define MVDU_REG_STAT_VDU_AVMP_OSD_AVMP_MASK	(1 << MVDU_REG_STAT_VDU_AVMP_OSD_AVMP_SHIFT)

#define MVDU_REG_STAT_VDU_FIFO			(MVDU_VDU_STATUS_BASE + 0x0C)

#define MVDU_REG_INT_VDU_ENA			(MVDU_VDU_INT_BASE + 0x04)
#define MVDU_REG_INT_VDU_STAT			(MVDU_VDU_INT_BASE + 0x08)
#define MVDU_REG_INT_VDU_STAT_I_FIFO_EMPTY_SHIFT 25
#define MVDU_REG_INT_VDU_STAT_I_FIFO_EMPTY_MASK	(1 << MVDU_REG_INT_VDU_STAT_I_FIFO_EMPTY_SHIFT)
#define MVDU_REG_INT_VDU_STAT_O_FIFO_EMPTY_SHIFT 24
#define MVDU_REG_INT_VDU_STAT_O_FIFO_EMPTY_MASK	(1 << MVDU_REG_INT_VDU_STAT_O_FIFO_EMPTY_SHIFT)
#define MVDU_REG_INT_VDU_STAT_H_SYNC_SHIFT	17
#define MVDU_REG_INT_VDU_STAT_H_SYNC_MASK	(1 << MVDU_REG_INT_VDU_STAT_H_SYNC_SHIFT)
#define MVDU_REG_INT_VDU_STAT_FR_PRC_END_SHIFT	10
#define MVDU_REG_INT_VDU_STAT_FR_PRC_END_MASK	(1 << MVDU_REG_INT_VDU_STAT_FR_PRC_END_SHIFT)
#define MVDU_REG_INT_VDU_STAT_MVL_FR_RD_END_SHIFT 9
#define MVDU_REG_INT_VDU_STAT_MVL_FR_RD_END_MASK (1 << MVDU_REG_INT_VDU_STAT_MVL_FR_RD_END_SHIFT)
#define MVDU_REG_INT_VDU_STAT_OSD_FR_RD_END_SHIFT 8
#define MVDU_REG_INT_VDU_STAT_OSD_FR_RD_END_MASK (1 << MVDU_REG_INT_VDU_STAT_OSD_FR_RD_END_SHIFT)
#define MVDU_REG_INT_VDU_STAT_VDU_OFF_SHIFT	1
#define MVDU_REG_INT_VDU_STAT_VDU_OFF_MASK	(1 << MVDU_REG_INT_VDU_STAT_VDU_OFF_SHIFT)
#define MVDU_REG_INT_VDU_STAT_INT_SYS_ERR_SHIFT	0
#define MVDU_REG_INT_VDU_STAT_INT_SYS_ERR_MASK	(1 << MVDU_REG_INT_VDU_STAT_INT_SYS_ERR_SHIFT)

#define MVDU_REG_SCALER_CTRL			(MVDU_VDU_SCALER_BASE + 0x04)
#define MVDU_REG_SCAL_DROP_POLAR_STR_SHIFT	25
#define MVDU_REG_SCAL_DROP_POLAR_STR_MASK	(1 << MVDU_REG_SCAL_DROP_POLAR_STR_SHIFT)
#define MVDU_REG_SCAL_DROP_ENA_STR_SHIFT	24
#define MVDU_REG_SCAL_DROP_ENA_STR_MASK		(1 << MVDU_REG_SCAL_DROP_ENA_STR_SHIFT)
#define MVDU_REG_SCALER_V_FLT_ENA_SHIFT		17
#define MVDU_REG_SCALER_V_FLT_ENA_MASK		(1 << MVDU_REG_SCALER_V_FLT_ENA_SHIFT)
#define MVDU_REG_SCALER_H_FLT_ENA_SHIFT		16
#define MVDU_REG_SCALER_H_FLT_ENA_MASK		(1 << MVDU_REG_SCALER_H_FLT_ENA_SHIFT)
#define MVDU_REG_SCALER_V_CUT_ENA_SHIFT		11
#define MVDU_REG_SCALER_V_CUT_ENA_MASK		(1 << MVDU_REG_SCALER_V_CUT_ENA_SHIFT)
#define MVDU_REG_SCALER_H_CUT_ENA_SHIFT		10
#define MVDU_REG_SCALER_H_CUT_ENA_MASK		(1 << MVDU_REG_SCALER_H_CUT_ENA_SHIFT)
#define MVDU_REG_SCALER_V_UPSIZE_SHIFT		9
#define MVDU_REG_SCALER_V_UPSIZE_MASK		(1 << MVDU_REG_SCALER_V_UPSIZE_SHIFT)
#define MVDU_REG_SCALER_H_UPSIZE_SHIFT		8
#define MVDU_REG_SCALER_H_UPSIZE_MASK		(1 << MVDU_REG_SCALER_H_UPSIZE_SHIFT)
#define MVDU_REG_SCALER_V_SCALER_ENA_SHIFT	1
#define MVDU_REG_SCALER_V_SCALER_ENA_MASK	(1 << MVDU_REG_SCALER_V_SCALER_ENA_SHIFT)
#define MVDU_REG_SCALER_H_SCALER_ENA_SHIFT	0
#define MVDU_REG_SCALER_H_SCALER_ENA_MASK	(1 << MVDU_REG_SCALER_H_SCALER_ENA_SHIFT)

#define MVDU_REG_SCALER_SCH_Y			(MVDU_VDU_SCALER_BASE + 0x08)
#define MVDU_REG_SCALER_SCV_Y			(MVDU_VDU_SCALER_BASE + 0x0C)
#define MVDU_REG_SCALER_SCH_C			(MVDU_VDU_SCALER_BASE + 0x10)
#define MVDU_REG_SCALER_SCV_C			(MVDU_VDU_SCALER_BASE + 0x14)

#define MVDU_REG_SCALER_SIZE_Y			(MVDU_VDU_SCALER_BASE + 0x18)
#define MVDU_REG_SCALER_SIZE_VY_SHIFT		16
#define MVDU_REG_SCALER_SIZE_VY_MASK		(0xFFF << MVDU_REG_SCALER_SIZE_VY_SHIFT)
#define MVDU_REG_SCALER_SIZE_HY_SHIFT		0
#define MVDU_REG_SCALER_SIZE_HY_MASK		(0xFFF << MVDU_REG_SCALER_SIZE_HY_SHIFT)

#define MVDU_REG_SCALER_SIZE_C			(MVDU_VDU_SCALER_BASE + 0x1C)
#define MVDU_REG_SCALER_SIZE_VC_SHIFT		16
#define MVDU_REG_SCALER_SIZE_VC_MASK		(0xFFF << MVDU_REG_SCALER_SIZE_VC_SHIFT)
#define MVDU_REG_SCALER_SIZE_HC_SHIFT		0
#define MVDU_REG_SCALER_SIZE_HC_MASK		(0xFFF << MVDU_REG_SCALER_SIZE_HC_SHIFT)

#define MVDU_REG_SCALER_FLT_Y_C0		(MVDU_VDU_SCALER_BASE + 0x20)
#define MVDU_REG_SCALER_FLT_C0_HY_SHIFT		0
#define MVDU_REG_SCALER_FLT_C0_HY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C0_HY_SHIFT)
#define MVDU_REG_SCALER_FLT_C0_VY_SHIFT		8
#define MVDU_REG_SCALER_FLT_C0_VY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C0_VY_SHIFT)

#define MVDU_REG_SCALER_FLT_Y_C1		(MVDU_VDU_SCALER_BASE + 0x24)
#define MVDU_REG_SCALER_FLT_C1_HY_SHIFT		0
#define MVDU_REG_SCALER_FLT_C1_HY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C1_HY_SHIFT)
#define MVDU_REG_SCALER_FLT_C1_VY_SHIFT		8
#define MVDU_REG_SCALER_FLT_C1_VY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C1_VY_SHIFT)

#define MVDU_REG_SCALER_FLT_Y_C2		(MVDU_VDU_SCALER_BASE + 0x28)
#define MVDU_REG_SCALER_FLT_C2_HY_SHIFT		0
#define MVDU_REG_SCALER_FLT_C2_HY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C2_HY_SHIFT)
#define MVDU_REG_SCALER_FLT_C2_VY_SHIFT		8
#define MVDU_REG_SCALER_FLT_C2_VY_MASK		(0xFF << MVDU_REG_SCALER_FLT_C2_VY_SHIFT)

#define MVDU_REG_SCALER_FLT_Y_C3		(MVDU_VDU_SCALER_BASE + 0x2C)
#define MVDU_REG_SCALER_FLT_Y_C4		(MVDU_VDU_SCALER_BASE + 0x30)

#define MVDU_REG_SCALER_FLT_NORM		(MVDU_VDU_SCALER_BASE + 0x48)
#define MVDU_REG_SCALER_HFLT_Y_N_SHIFT		0
#define MVDU_REG_SCALER_HFLT_Y_N_MASK		(0xFF << MVDU_REG_SCALER_HFLT_Y_N_SHIFT)
#define MVDU_REG_SCALER_VFLT_Y_N_SHIFT		0
#define MVDU_REG_SCALER_VFLT_Y_N_MASK		(0xFF << MVDU_REG_SCALER_VFLT_Y_N_SHIFT)
#define MVDU_REG_SCALER_HFLT_C_N_SHIFT		0
#define MVDU_REG_SCALER_HFLT_C_N_MASK		(0xFF << MVDU_REG_SCALER_HFLT_C_N_SHIFT)
#define MVDU_REG_SCALER_VFLT_C_N_SHIFT		0
#define MVDU_REG_SCALER_VFLT_C_N_MASK		(0xFF << MVDU_REG_SCALER_VFLT_C_N_SHIFT)

#define MVDU_REG_SCALER_FLT_C_C0		(MVDU_VDU_SCALER_BASE + 0x4C)
#define MVDU_REG_SCALER_FLT_C0_HC_SHIFT		0
#define MVDU_REG_SCALER_FLT_C0_HC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C0_HC_SHIFT)
#define MVDU_REG_SCALER_FLT_C0_VC_SHIFT		8
#define MVDU_REG_SCALER_FLT_C0_VC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C0_VC_SHIFT)

#define MVDU_REG_SCALER_FLT_C_C1		(MVDU_VDU_SCALER_BASE + 0x50)
#define MVDU_REG_SCALER_FLT_C1_HC_SHIFT		0
#define MVDU_REG_SCALER_FLT_C1_HC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C1_HC_SHIFT)
#define MVDU_REG_SCALER_FLT_C1_VC_SHIFT		8
#define MVDU_REG_SCALER_FLT_C1_VC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C1_VC_SHIFT)

#define MVDU_REG_SCALER_FLT_C_C2		(MVDU_VDU_SCALER_BASE + 0x54)
#define MVDU_REG_SCALER_FLT_C2_HC_SHIFT		0
#define MVDU_REG_SCALER_FLT_C2_HC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C2_HC_SHIFT)
#define MVDU_REG_SCALER_FLT_C2_VC_SHIFT		8
#define MVDU_REG_SCALER_FLT_C2_VC_MASK		(0xFF << MVDU_REG_SCALER_FLT_C2_VC_SHIFT)

#define MVDU_REG_SCALER_FLT_C_C3		(MVDU_VDU_SCALER_BASE + 0x58)
#define MVDU_REG_SCALER_FLT_C_C4		(MVDU_VDU_SCALER_BASE + 0x5C)
#define MVDU_REG_SCALER_PHS_CUT_V		(MVDU_VDU_SCALER_BASE + 0x70)

#define MVDU_REG_SCALER_SIZE_CUT		(MVDU_VDU_SCALER_BASE + 0x74)
#define MVDU_REG_SCALER_SIZE_CUT_V_SHIFT	16
#define MVDU_REG_SCALER_SIZE_CUT_V_MASK		(0x7FF << MVDU_REG_SCALER_SIZE_CUT_V_SHIFT)
#define MVDU_REG_SCALER_SIZE_CUT_H_SHIFT	0
#define MVDU_REG_SCALER_SIZE_CUT_H_MASK		(0x7FF << MVDU_REG_SCALER_SIZE_CUT_H_SHIFT)

#define MVDU_REG_SCALER_PHS_CUT_H		(MVDU_VDU_SCALER_BASE + 0x78)
#define MVDU_REG_SCALER_CUT_H_L_SHIFT		16
#define MVDU_REG_SCALER_CUT_H_L_MASK		(0x7FF << MVDU_REG_SCALER_CUT_H_L_SHIFT)
#define MVDU_REG_SCALER_CUT_H_R_SHIFT		0
#define MVDU_REG_SCALER_CUT_H_R_MASK		(0x7FF << MVDU_REG_SCALER_CUT_H_R_SHIFT)

#define MVDU_REG_SCALER_MVL_CLR_Y		(MVDU_VDU_SCALER_BASE + 0x7C)
#define MVDU_REG_SCALER_MVL_CLR_Y_Cr_SHIFT	20
#define MVDU_REG_SCALER_MVL_CLR_Y_Cr_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Y_Cr_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Y_Cb_SHIFT	10
#define MVDU_REG_SCALER_MVL_CLR_Y_Cb_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Y_Cb_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Y_Y_SHIFT	0
#define MVDU_REG_SCALER_MVL_CLR_Y_Y_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Y_Y_SHIFT)

#define MVDU_REG_SCALER_MVL_CLR_Cb		(MVDU_VDU_SCALER_BASE + 0x80)
#define MVDU_REG_SCALER_MVL_CLR_Cb_Cr_SHIFT	20
#define MVDU_REG_SCALER_MVL_CLR_Cb_Cr_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cb_Cr_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Cb_Cb_SHIFT	10
#define MVDU_REG_SCALER_MVL_CLR_Cb_Cb_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cb_Cb_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Cb_Y_SHIFT	0
#define MVDU_REG_SCALER_MVL_CLR_Cb_Y_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cb_Y_SHIFT)

#define MVDU_REG_SCALER_MVL_CLR_Cr		(MVDU_VDU_SCALER_BASE + 0x84)
#define MVDU_REG_SCALER_MVL_CLR_Cr_Cr_SHIFT	20
#define MVDU_REG_SCALER_MVL_CLR_Cr_Cr_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cr_Cr_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Cr_Cb_SHIFT	10
#define MVDU_REG_SCALER_MVL_CLR_Cr_Cb_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cr_Cb_SHIFT)
#define MVDU_REG_SCALER_MVL_CLR_Cr_Y_SHIFT	0
#define MVDU_REG_SCALER_MVL_CLR_Cr_Y_MASK	(0x3FF << MVDU_REG_SCALER_MVL_CLR_Cr_Y_SHIFT)



#define MVDU_REG_DIF_MVL_START			(MVDU_VDU_DIF_BASE + 0x0C)
#define MVDU_REG_DIF_MVL_START_H_SHIFT		0
#define MVDU_REG_DIF_MVL_START_H_MASK		(0x7FF << MVDU_REG_DIF_MVL_START_H_SHIFT)
#define MVDU_REG_DIF_MVL_START_V_SHIFT		16
#define MVDU_REG_DIF_MVL_START_V_MASK		(0x7FF << MVDU_REG_DIF_MVL_START_V_SHIFT)





#define MVDU_REG_OSD_BASEreg0			(MVDU_VDU_OSD_BASE + 0x00)
#define MVDU_REG_OSD_BASEreg1			(MVDU_VDU_OSD_BASE + 0x04)

#define MVDU_REG_OSD_COLOR_Y			(MVDU_VDU_OSD_BASE + 0x08)
#define MVDU_REG_OSD_COLOR_Y_R_SHIFT		0
#define MVDU_REG_OSD_COLOR_Y_R_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Y_R_SHIFT)
#define MVDU_REG_OSD_COLOR_Y_G_SHIFT		10
#define MVDU_REG_OSD_COLOR_Y_G_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Y_G_SHIFT)
#define MVDU_REG_OSD_COLOR_Y_B_SHIFT		20
#define MVDU_REG_OSD_COLOR_Y_B_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Y_B_SHIFT)

#define MVDU_REG_OSD_COLOR_Cb			(MVDU_VDU_OSD_BASE + 0x0C)
#define MVDU_REG_OSD_COLOR_Cb_R_SHIFT		0
#define MVDU_REG_OSD_COLOR_Cb_R_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cb_R_SHIFT)
#define MVDU_REG_OSD_COLOR_Cb_G_SHIFT		10
#define MVDU_REG_OSD_COLOR_Cb_G_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cb_G_SHIFT)
#define MVDU_REG_OSD_COLOR_Cb_B_SHIFT		20
#define MVDU_REG_OSD_COLOR_Cb_B_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cb_B_SHIFT)

#define MVDU_REG_OSD_COLOR_Cr			(MVDU_VDU_OSD_BASE + 0x10)
#define MVDU_REG_OSD_COLOR_Cr_R_SHIFT		0
#define MVDU_REG_OSD_COLOR_Cr_R_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cr_R_SHIFT)
#define MVDU_REG_OSD_COLOR_Cr_G_SHIFT		10
#define MVDU_REG_OSD_COLOR_Cr_G_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cr_G_SHIFT)
#define MVDU_REG_OSD_COLOR_Cr_B_SHIFT		20
#define MVDU_REG_OSD_COLOR_Cr_B_MASK		(0x1FF << MVDU_REG_OSD_COLOR_Cr_B_SHIFT)

#define MVDU_REG_OSD_FIFO_END			(MVDU_VDU_OSD_BASE + 0x14)
#define MVDU_REG_OSD_CTRL			(MVDU_VDU_OSD_BASE + 0x18)

#define MVDU_REG_MI_CTRL			(MVDU_VDU_MI_BASE + 0x04)
#define MVDU_REG_MI_CTRL_BUF_BIT_ENDIAN_SHIFT	16
#define MVDU_REG_MI_CTRL_BUF_BIT_ENDIAN_MASK	(1 << MVDU_REG_MI_CTRL_BUF_BIT_ENDIAN_SHIFT)
#define MVDU_REG_MI_CTRL_YCbCr_FORMAT_SHIFT	9
#define MVDU_REG_MI_CTRL_YCbCr_FORMAT_MASK	(1 << MVDU_REG_MI_CTRL_YCbCr_FORMAT_SHIFT)
#define MVDU_REG_MI_CTRL_PLANE_NUM_SHIFT	8
#define MVDU_REG_MI_CTRL_PLANE_NUM_MASK		(1 << MVDU_REG_MI_CTRL_PLANE_NUM_SHIFT)
#define MVDU_REG_MI_CTRL_PLANE_ACCESS_SHIFT	2
#define MVDU_REG_MI_CTRL_PLANE_ACCESS_MASK	(1 << MVDU_REG_MI_CTRL_PLANE_ACCESS_SHIFT)
#define MVDU_REG_MI_CTRL_FILD_ACCESS_SHIFT	1
#define MVDU_REG_MI_CTRL_FILD_ACCESS_MASK	(1 << MVDU_REG_MI_CTRL_FILD_ACCESS_SHIFT)

#define MVDU_REG_MI_MVL_Y_BAreg0		(MVDU_VDU_MI_BASE + 0x08)
#define MVDU_REG_MI_MVL_Cb_BAreg0		(MVDU_VDU_MI_BASE + 0x0C)
#define MVDU_REG_MI_MVL_Cr_BAreg0		(MVDU_VDU_MI_BASE + 0x10)
#define MVDU_REG_MI_MVL_Y_BAreg1		(MVDU_VDU_MI_BASE + 0x14)
#define MVDU_REG_MI_MVL_Cb_BAreg1		(MVDU_VDU_MI_BASE + 0x18)
#define MVDU_REG_MI_MVL_Cr_BAreg1		(MVDU_VDU_MI_BASE + 0x1C)

#define MVDU_REG_MI_MVL_Y_SIZE			(MVDU_VDU_MI_BASE + 0x20)
#define MVDU_REG_MI_MVL_Y_V_SIZE_SHIFT		16
#define MVDU_REG_MI_MVL_Y_V_SIZE_MASK		(0x7FF << MVDU_REG_MI_MVL_Y_V_SIZE_SHIFT)
#define MVDU_REG_MI_MVL_Y_H_SIZE_SHIFT		0
#define MVDU_REG_MI_MVL_Y_H_SIZE_MASK		(0x7FF << MVDU_REG_MI_MVL_Y_H_SIZE_SHIFT)

#define MVDU_REG_MI_MVL_C_SIZE			(MVDU_VDU_MI_BASE + 0x24)
#define MVDU_REG_MI_MVL_C_V_SIZE_SHIFT		16
#define MVDU_REG_MI_MVL_C_V_SIZE_MASK		(0x7FF << MVDU_REG_MI_MVL_C_V_SIZE_SHIFT)
#define MVDU_REG_MI_MVL_C_H_SIZE_SHIFT		0
#define MVDU_REG_MI_MVL_C_H_SIZE_MASK		(0x7FF << MVDU_REG_MI_MVL_C_H_SIZE_SHIFT)

#define MVDU_REG_MI_MVL_FULL_SIZE		(MVDU_VDU_MI_BASE + 0x28)
#define MVDU_REG_MI_MVL_C_FULL_SIZE_SHIFT	16
#define MVDU_REG_MI_MVL_C_FULL_SIZE_MASK	(0x1FFF << MVDU_REG_MI_MVL_C_FULL_SIZE_SHIFT)
#define MVDU_REG_MI_MVL_Y_FULL_SIZE_SHIFT	0
#define MVDU_REG_MI_MVL_Y_FULL_SIZE_MASK	(0x1FFF << MVDU_REG_MI_MVL_Y_FULL_SIZE_SHIFT)

#define MVDU_REG_MI_AXI_MVL_PARAM		(MVDU_VDU_MI_BASE + 0x2C)
#define MVDU_REG_MI_MVL_FIFO_START		(MVDU_VDU_MI_BASE + 0x30)
#define MVDU_REG_MI_MVL_FIFO_END		(MVDU_VDU_MI_BASE + 0x34)
#define MVDU_REG_MI_AXI_OSD_PARAM		(MVDU_VDU_MI_BASE + 0x38)


// ???

// ???
#define MVDU_VIDEO_IN_MIN_WIDTH		160
#define MVDU_VIDEO_IN_MAX_WIDTH		1920
#define MVDU_VIDEO_IN_MIN_HEIGHT	100
#define MVDU_VIDEO_IN_MAX_HEIGHT	1080
