/*
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 as published
 *  by the Free Software Foundation.
 *
 *  Copyright (C) 2020 Mikhail Petrov <Mikhail.Petrov@mir.dev>
 */

#define VDU_REG_SECOND_CORE_BASE 0x1000


#define VDU_REG_CTRL_BASE 0x000
#define VDU_REG_INT_BASE 0x300
#define VDU_REG_SCALER_BASE 0x400
#define VDU_REG_DIF_BASE 0x500
#define VDU_REG_OSD_BASE 0x700
#define VDU_REG_MI_BASE 0x900


#define VDU_REG_CTRL_VDU_ID (VDU_REG_CTRL_BASE + 0x04)
#define VDU_REG_CTRL_ENA (VDU_REG_CTRL_BASE + 0x08)
#define VDU_REG_CTRL_SOFT_RESET (VDU_REG_CTRL_BASE + 0x0C)

#define VDU_REG_CTRL_ENA_VDU_ENA_MASK (1 << 0)
#define VDU_REG_CTRL_ENA_OSD_ENA_MASK (1 << 1)
#define VDU_REG_CTRL_ENA_MVL_ENA_MASK (1 << 2)
#define VDU_REG_CTRL_ENA_OSD_BASE_SW_ENA_MASK (1 << 8)
#define VDU_REG_CTRL_ENA_MVL_BASE_SW_ENA_MASK (1 << 9)

#define VDU_REG_CTRL_SOFT_RESET_MASK (1 << 0)


#define VDU_REG_INT_ENA (VDU_REG_INT_BASE + 0x04)
#define VDU_REG_INT_STAT (VDU_REG_INT_BASE + 0x08)

#define VDU_REG_INT_VDU_ENA_MASK (1 << 1)
#define VDU_REG_INT_VDU_STAT_SA_MASK (1 << 18)


#define VDU_REG_SCALER_CTRL (VDU_REG_SCALER_BASE + 0x04)
#define VDU_REG_SCALER_SCH_Y (VDU_REG_SCALER_BASE + 0x08)
#define VDU_REG_SCALER_SCV_Y (VDU_REG_SCALER_BASE + 0x0C)
#define VDU_REG_SCALER_SCH_C (VDU_REG_SCALER_BASE + 0x10)
#define VDU_REG_SCALER_SCV_C (VDU_REG_SCALER_BASE + 0x14)
#define VDU_REG_SCALER_SIZE_Y (VDU_REG_SCALER_BASE + 0x18)
#define VDU_REG_SCALER_SIZE_C (VDU_REG_SCALER_BASE + 0x1C)
#define VDU_REG_SCALER_FLT_Y_C0 (VDU_REG_SCALER_BASE + 0x20)
#define VDU_REG_SCALER_FLT_Y_C1 (VDU_REG_SCALER_BASE + 0x24)
#define VDU_REG_SCALER_FLT_Y_C2 (VDU_REG_SCALER_BASE + 0x28)
#define VDU_REG_SCALER_FLT_Y_C3 (VDU_REG_SCALER_BASE + 0x2C)
#define VDU_REG_SCALER_FLT_Y_C4 (VDU_REG_SCALER_BASE + 0x30)
#define VDU_REG_SCALER_FLT_NORM (VDU_REG_SCALER_BASE + 0x48)
#define VDU_REG_SCALER_FLT_C_C0 (VDU_REG_SCALER_BASE + 0x4C)
#define VDU_REG_SCALER_FLT_C_C1 (VDU_REG_SCALER_BASE + 0x50)
#define VDU_REG_SCALER_FLT_C_C2 (VDU_REG_SCALER_BASE + 0x54)
#define VDU_REG_SCALER_FLT_C_C3 (VDU_REG_SCALER_BASE + 0x58)
#define VDU_REG_SCALER_FLT_C_C4 (VDU_REG_SCALER_BASE + 0x5C)
#define VDU_REG_SCALER_PHS_CUT_V (VDU_REG_SCALER_BASE + 0x70)
#define VDU_REG_SCALER_SIZE_CUT (VDU_REG_SCALER_BASE + 0x74)
#define VDU_REG_SCALER_PHS_CUT_H (VDU_REG_SCALER_BASE + 0x78)
#define VDU_REG_SCALER_MVL_CLR_Y (VDU_REG_SCALER_BASE + 0x7C)
#define VDU_REG_SCALER_MVL_CLR_CB (VDU_REG_SCALER_BASE + 0x80)
#define VDU_REG_SCALER_MVL_CLR_CR (VDU_REG_SCALER_BASE + 0x84)

#define VDU_REG_SCALER_CTRL_V_FLT_ENA_MASK (1 << 17)
#define VDU_REG_SCALER_CTRL_H_FLT_ENA_MASK (1 << 16)
#define VDU_REG_SCALER_CTRL_V_SCALER_ENA_MASK (1 << 1)
#define VDU_REG_SCALER_CTRL_H_SCALER_ENA_MASK (1 << 0)

#define VDU_REG_SCALER_SCH_Y_MASK 0xFFFFF
#define VDU_REG_SCALER_SCV_Y_MASK 0xFFFFF

#define VDU_REG_SCALER_SIZE_Y_H_SHIFT 0
#define VDU_REG_SCALER_SIZE_Y_V_SHIFT 16

#define VDU_REG_SCALER_SIZE_C_H_SHIFT 0
#define VDU_REG_SCALER_SIZE_C_V_SHIFT 16

#define VDU_REG_SCALER_FLT_Y_C_H_SHIFT 0
#define VDU_REG_SCALER_FLT_Y_C_V_SHIFT 8

#define VDU_REG_SCALER_FLT_NORM_HFLT_Y_N_SHIFT 0
#define VDU_REG_SCALER_FLT_NORM_VFLT_Y_N_SHIFT 8
#define VDU_REG_SCALER_FLT_NORM_HFLT_C_N_SHIFT 16
#define VDU_REG_SCALER_FLT_NORM_VFLT_C_N_SHIFT 24

#define VDU_REG_SCALER_FLT_C_C_H_SHIFT 0
#define VDU_REG_SCALER_FLT_C_C_V_SHIFT 8

#define VDU_REG_SCALER_SIZE_CUT_H_SHIFT 0
#define VDU_REG_SCALER_SIZE_CUT_V_SHIFT 16

#define VDU_REG_SCALER_MVL_CLR_Y_Y_SHIFT 0
#define VDU_REG_SCALER_MVL_CLR_Y_CB_SHIFT 10
#define VDU_REG_SCALER_MVL_CLR_Y_CR_SHIFT 20

#define VDU_REG_SCALER_MVL_CLR_CB_Y_SHIFT 0
#define VDU_REG_SCALER_MVL_CLR_CB_CB_SHIFT 10
#define VDU_REG_SCALER_MVL_CLR_CB_CR_SHIFT 20

#define VDU_REG_SCALER_MVL_CLR_CR_Y_SHIFT 0
#define VDU_REG_SCALER_MVL_CLR_CR_CB_SHIFT 10
#define VDU_REG_SCALER_MVL_CLR_CR_CR_SHIFT 20


#define VDU_REG_DIF_CTRL (VDU_REG_DIF_BASE + 0x04)
#define VDU_REG_DIF_BGR (VDU_REG_DIF_BASE + 0x08)
#define VDU_REG_DIF_MVL_START (VDU_REG_DIF_BASE + 0x0C)
#define VDU_REG_DIF_BLANK (VDU_REG_DIF_BASE + 0x10)
#define VDU_REG_DIF_FSIZE (VDU_REG_DIF_BASE + 0x14)
#define VDU_REG_DIF_ASIZE (VDU_REG_DIF_BASE + 0x18)
#define VDU_REG_DIF_HSYNC (VDU_REG_DIF_BASE + 0x1C)
#define VDU_REG_DIF_VSYNC (VDU_REG_DIF_BASE + 0x20)

#define VDU_REG_DIF_CTRL_VREFRESH_50_HZ_MASK (1 << 0)
#define VDU_REG_DIF_CTRL_NO_INTERLACE_MASK (1 << 1)
#define VDU_REG_DIF_CTRL_HDTV_MASK (1 << 4)
#define VDU_REG_DIF_CTRL_EXT_SYNC_EN_MASK (1 << 9)
#define VDU_REG_DIF_CTRL_SDTV_FORM_MASK (1 << 10)
#define VDU_REG_DIF_CTRL_HSYNC_P_MASK (1 << 16)
#define VDU_REG_DIF_CTRL_VSYNC_P_MASK (1 << 17)
#define VDU_REG_DIF_CTRL_CH_SEL (1 << 24)
#define VDU_REG_DIF_CTRL_444_MODE_MASK (1 << 31)

#define VDU_REG_DIF_BGR_CR_SHIFT 0
#define VDU_REG_DIF_BGR_CB_SHIFT 8
#define VDU_REG_DIF_BGR_Y_SHIFT 16

#define VDU_REG_DIF_MVL_START_H_SHIFT 0
#define VDU_REG_DIF_MVL_START_V_SHIFT 16

#define VDU_REG_DIF_BLANK_HBLANK_SHIFT 0
#define VDU_REG_DIF_BLANK_HBLANK_BITS 10
#define VDU_REG_DIF_BLANK_VBLANK_BEG_SHIFT 16
#define VDU_REG_DIF_BLANK_VBLANK_BEG_BITS 6
#define VDU_REG_DIF_BLANK_VBLANK_END_SHIFT 24

#define VDU_REG_DIF_FSIZE_HTOTAL_SHIFT 0
#define VDU_REG_DIF_FSIZE_HTOTAL_BITS 12
#define VDU_REG_DIF_FSIZE_VTOTAL_SHIFT 16
#define VDU_REG_DIF_FSIZE_VTOTAL_BITS 11

#define VDU_REG_DIF_ASIZE_HACTIVE_SHIFT 0
#define VDU_REG_DIF_ASIZE_VACTIVE_SHIFT 16

#define VDU_REG_DIF_HSYNC_START_SHIFT 0
#define VDU_REG_DIF_HSYNC_START_BITS 10
#define VDU_REG_DIF_HSYNC_LEN_SHIFT 16
#define VDU_REG_DIF_HSYNC_LEN_BITS 8
#define VDU_REG_DIF_HSYNC_DELAY_SHIFT 24
#define VDU_REG_DIF_HSYNC_DELAY_BITS 8

#define VDU_REG_DIF_VSYNC_START_SHIFT 0
#define VDU_REG_DIF_VSYNC_START_BITS 3
#define VDU_REG_DIF_VSYNC_LEN_SHIFT 16
#define VDU_REG_DIF_VSYNC_LEN_BITS 3


#define VDU_REG_OSD_BASE0 (VDU_REG_OSD_BASE + 0x00)
#define VDU_REG_OSD_BASE1 (VDU_REG_OSD_BASE + 0x04)
#define VDU_REG_OSD_COLOR_Y (VDU_REG_OSD_BASE + 0x08)
#define VDU_REG_OSD_COLOR_CB (VDU_REG_OSD_BASE + 0x0C)
#define VDU_REG_OSD_COLOR_CR (VDU_REG_OSD_BASE + 0x10)
#define VDU_REG_OSD_CTRL (VDU_REG_OSD_BASE + 0x18)

#define VDU_REG_OSD_COLOR_Y_R_SHIFT 0
#define VDU_REG_OSD_COLOR_Y_G_SHIFT 10
#define VDU_REG_OSD_COLOR_Y_B_SHIFT 20

#define VDU_REG_OSD_COLOR_CB_R_SHIFT 0
#define VDU_REG_OSD_COLOR_CB_G_SHIFT 10
#define VDU_REG_OSD_COLOR_CB_B_SHIFT 20

#define VDU_REG_OSD_COLOR_CR_R_SHIFT 0
#define VDU_REG_OSD_COLOR_CR_G_SHIFT 10
#define VDU_REG_OSD_COLOR_CR_B_SHIFT 20

#define VDU_REG_OSD_CTRL_ARGB_RGBA_MASK (1 << 0)


#define VDU_REG_MI_CTRL (VDU_REG_MI_BASE + 0x04)
#define VDU_REG_MI_MVL_Y_BASE0 (VDU_REG_MI_BASE + 0x08)
#define VDU_REG_MI_MVL_CB_BASE0 (VDU_REG_MI_BASE + 0x0C)
#define VDU_REG_MI_MVL_CR_BASE0 (VDU_REG_MI_BASE + 0x10)
#define VDU_REG_MI_MVL_Y_BASE1 (VDU_REG_MI_BASE + 0x14)
#define VDU_REG_MI_MVL_CB_BASE1 (VDU_REG_MI_BASE + 0x18)
#define VDU_REG_MI_MVL_CR_BASE1 (VDU_REG_MI_BASE + 0x1C)
#define VDU_REG_MI_MVL_Y_SIZE (VDU_REG_MI_BASE + 0x20)
#define VDU_REG_MI_MVL_C_SIZE (VDU_REG_MI_BASE + 0x24)
#define VDU_REG_MI_MVL_FULL_SIZE (VDU_REG_MI_BASE + 0x28)
#define VDU_REG_MI_AXI_MVL_PARAM (VDU_REG_MI_BASE + 0x2C)
#define VDU_REG_MI_AXI_OSD_PARAM (VDU_REG_MI_BASE + 0x38)

#define VDU_REG_MI_CTRL_PLANE_NUM_MASK (1 << 8)

#define VDU_REG_MI_MVL_Y_SIZE_V_SHIFT 16
#define VDU_REG_MI_MVL_Y_SIZE_H_SHIFT 0

#define VDU_REG_MI_MVL_C_SIZE_V_SHIFT 16
#define VDU_REG_MI_MVL_C_SIZE_H_SHIFT 0

#define VDU_REG_MI_MVL_FULL_SIZE_C_SHIFT 16
#define VDU_REG_MI_MVL_FULL_SIZE_Y_SHIFT 0
