/*
 *  This program is free software; you can redistribute it and/or modify it
 *  under the terms of the GNU General Public License version 2 as published
 *  by the Free Software Foundation.
 *
 *  Copyright (C) 2020 Mikhail Petrov <Mikhail.Petrov@mir.dev>
 */

#define VDU_REG_CTRL_BASE 0x000
#define VDU_REG_INT_BASE 0x300
#define VDU_REG_DIF_BASE 0x500
#define VDU_REG_OSD_BASE 0x700
#define VDU_REG_MI_BASE 0x900


#define VDU_REG_CTRL_VDU_ID (VDU_REG_CTRL_BASE + 0x04)
#define VDU_REG_CTRL_ENA (VDU_REG_CTRL_BASE + 0x08)
#define VDU_REG_CTRL_SOFT_RESET (VDU_REG_CTRL_BASE + 0x0C)

#define VDU_REG_CTRL_ENA_VDU_ENA_MASK (1 << 0)
#define VDU_REG_CTRL_ENA_OSD_ENA_MASK (1 << 1)
#define VDU_REG_CTRL_ENA_OSD_BASE_SW_ENA_MASK (1 << 8)

#define VDU_REG_CTRL_SOFT_RESET_MASK (1 << 0)


#define VDU_REG_INT_ENA (VDU_REG_INT_BASE + 0x04)
#define VDU_REG_INT_STAT (VDU_REG_INT_BASE + 0x08)

#define VDU_REG_INT_VDU_ENA_MASK (1 << 1)
#define VDU_REG_INT_VDU_STAT_SA_MASK (1 << 18)


#define VDU_REG_DIF_CTRL (VDU_REG_DIF_BASE + 0x04)
#define VDU_REG_DIF_BGR (VDU_REG_DIF_BASE + 0x08)
#define VDU_REG_DIF_BLANK (VDU_REG_DIF_BASE + 0x10)
#define VDU_REG_DIF_FSIZE (VDU_REG_DIF_BASE + 0x14)
#define VDU_REG_DIF_ASIZE (VDU_REG_DIF_BASE + 0x18)
#define VDU_REG_DIF_HSYNC (VDU_REG_DIF_BASE + 0x1C)
#define VDU_REG_DIF_VSYNC (VDU_REG_DIF_BASE + 0x20)

#define VDU_REG_DIF_CTRL_VREFRESH_50_HZ_MASK (1 << 0)
#define VDU_REG_DIF_CTRL_NO_INTERLACE_MASK (1 << 1)
#define VDU_REG_DIF_CTRL_HDTV_MASK (1 << 4)
#define VDU_REG_DIF_CTRL_EXT_SYNC_EN_MASK (1 << 9)
#define VDU_REG_DIF_CTRL_SDTV_FORM_MASK (1 << 10)
#define VDU_REG_DIF_CTRL_HSYNC_P_MASK (1 << 16)
#define VDU_REG_DIF_CTRL_VSYNC_P_MASK (1 << 17)
#define VDU_REG_DIF_CTRL_DIF_444_MODE_MASK (1 << 31)

#define VDU_REG_DIF_BGR_CR_SHIFT 0
#define VDU_REG_DIF_BGR_CB_SHIFT 8
#define VDU_REG_DIF_BGR_Y_SHIFT 16

#define VDU_REG_DIF_BLANK_HBLANK_SHIFT 0
#define VDU_REG_DIF_BLANK_HBLANK_BITS 10
#define VDU_REG_DIF_BLANK_VBLANK_BEG_SHIFT 16
#define VDU_REG_DIF_BLANK_VBLANK_BEG_BITS 6
#define VDU_REG_DIF_BLANK_VBLANK_END_SHIFT 24

#define VDU_REG_DIF_FSIZE_HTOTAL_SHIFT 0
#define VDU_REG_DIF_FSIZE_HTOTAL_BITS 12
#define VDU_REG_DIF_FSIZE_VTOTAL_SHIFT 16
#define VDU_REG_DIF_FSIZE_VTOTAL_BITS 11

#define VDU_REG_DIF_ASIZE_HACTIVE_SHIFT 0
#define VDU_REG_DIF_ASIZE_VACTIVE_SHIFT 16

#define VDU_REG_DIF_HSYNC_START_SHIFT 0
#define VDU_REG_DIF_HSYNC_START_BITS 10
#define VDU_REG_DIF_HSYNC_LEN_SHIFT 16
#define VDU_REG_DIF_HSYNC_LEN_BITS 8
#define VDU_REG_DIF_HSYNC_DELAY_SHIFT 24
#define VDU_REG_DIF_HSYNC_DELAY_BITS 8

#define VDU_REG_DIF_VSYNC_START_SHIFT 0
#define VDU_REG_DIF_VSYNC_START_BITS 3
#define VDU_REG_DIF_VSYNC_LEN_SHIFT 16
#define VDU_REG_DIF_VSYNC_LEN_BITS 3


#define VDU_REG_OSD_BASE0 (VDU_REG_OSD_BASE + 0x00)
#define VDU_REG_OSD_BASE1 (VDU_REG_OSD_BASE + 0x04)
#define VDU_REG_OSD_COLOR_Y (VDU_REG_OSD_BASE + 0x08)
#define VDU_REG_OSD_COLOR_CB (VDU_REG_OSD_BASE + 0x0C)
#define VDU_REG_OSD_COLOR_CR (VDU_REG_OSD_BASE + 0x10)
#define VDU_REG_OSD_CTRL (VDU_REG_OSD_BASE + 0x18)

#define VDU_REG_OSD_COLOR_Y_R_SHIFT 0
#define VDU_REG_OSD_COLOR_Y_G_SHIFT 10
#define VDU_REG_OSD_COLOR_Y_B_SHIFT 20

#define VDU_REG_OSD_COLOR_CB_R_SHIFT 0
#define VDU_REG_OSD_COLOR_CB_G_SHIFT 10
#define VDU_REG_OSD_COLOR_CB_B_SHIFT 20

#define VDU_REG_OSD_COLOR_CR_R_SHIFT 0
#define VDU_REG_OSD_COLOR_CR_G_SHIFT 10
#define VDU_REG_OSD_COLOR_CR_B_SHIFT 20

#define VDU_REG_OSD_CTRL_ARGB_RGBA_MASK (1 << 0)


#define VDU_REG_MI_AXI_MVL_PARAM (VDU_REG_MI_BASE + 0x2C)
#define VDU_REG_MI_AXI_OSD_PARAM (VDU_REG_MI_BASE + 0x38)
